[project]
name = "Example"
version = "0.1.0"

[input]
glob = "include/**/*.hpp"
compiler_arguments = ["-Iinclude", "-std=gnu++20", "-xc++"]

[pages]
index = "README.md"
extra = ["extra-pages/extra-page.md"]

[output]
static_dir = "static"
path = "docs"
base_url = "/cppdoc"

[doctests]
enable = false 
